# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assessmentTool.ui'
#
# Created: Sat Jul 28 23:15:13 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!
import sys

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s


try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_main(QtGui.QFrame):
    def __init__(self):
        super(Ui_main,self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, main):
        main.setObjectName(_fromUtf8("main"))
        main.setWindowModality(QtCore.Qt.NonModal)
        main.resize(1123, 820)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setLayoutDirection(QtCore.Qt.LeftToRight)
        main.setFrameShape(QtGui.QFrame.StyledPanel)
        main.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(main)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.top = QtGui.QFrame(main)
        self.top.setAutoFillBackground(False)
        self.top.setStyleSheet(_fromUtf8(""))
        self.top.setFrameShape(QtGui.QFrame.StyledPanel)
        self.top.setFrameShadow(QtGui.QFrame.Raised)
        self.top.setObjectName(_fromUtf8("top"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.top)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.top)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.top)
        self.bottom = QtGui.QFrame(main)
        self.bottom.setAutoFillBackground(False)
        self.bottom.setStyleSheet(_fromUtf8(""))
        self.bottom.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bottom.setFrameShadow(QtGui.QFrame.Raised)
        self.bottom.setObjectName(_fromUtf8("bottom"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.bottom)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.left = QtGui.QFrame(self.bottom)
        self.left.setStyleSheet(_fromUtf8(""))
        self.left.setFrameShape(QtGui.QFrame.StyledPanel)
        self.left.setFrameShadow(QtGui.QFrame.Raised)
        self.left.setObjectName(_fromUtf8("left"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.left)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.button_panel = QtGui.QFrame(self.left)
        self.button_panel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.button_panel.setFrameShadow(QtGui.QFrame.Raised)
        self.button_panel.setObjectName(_fromUtf8("button_panel"))
        self.pushButton = QtGui.QPushButton(self.button_panel)
        self.pushButton.setGeometry(QtCore.QRect(30, 10, 111, 41))
        self.pushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.button_panel)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 10, 111, 41))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.button_panel)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 10, 111, 41))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_2.addWidget(self.button_panel)
        self.frame = QtGui.QFrame(self.left)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 12)
        self.horizontalLayout_5.addWidget(self.left)
        self.right = QtGui.QFrame(self.bottom)
        self.right.setStyleSheet(_fromUtf8(""))
        self.right.setFrameShape(QtGui.QFrame.StyledPanel)
        self.right.setFrameShadow(QtGui.QFrame.Raised)
        self.right.setObjectName(_fromUtf8("right"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.right)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_2 = QtGui.QFrame(self.right)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(40, 115, 34, 10)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tableWidget = QtGui.QTableWidget(self.frame_4)
        self.tableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 2, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(89)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(49)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.tableWidget_2 = QtGui.QTableWidget(self.frame_5)
        self.tableWidget_2.setGeometry(QtCore.QRect(41, 0, 222, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setAutoScroll(True)
        self.tableWidget_2.setAutoScrollMargin(0)
        self.tableWidget_2.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.tableWidget_2.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_2.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setRowCount(1)
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(44)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(0)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.verticalLayout_4.setStretch(0, 3)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.right)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 3)
        self.horizontalLayout_5.addWidget(self.right)
        self.horizontalLayout_5.setStretch(0, 9)
        self.horizontalLayout_5.setStretch(1, 8)
        self.verticalLayout.addWidget(self.bottom)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 15)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)
        main.setTabOrder(self.pushButton_2, self.pushButton_3)
        main.setTabOrder(self.pushButton_3, self.pushButton)

    def retranslateUi(self, main):
        main.setWindowTitle(_translate("main", "混合业务性能评估工具", None))
        self.label.setText(_translate("main", "混合业务性能评估工具", None))
        self.pushButton.setText(_translate("main", "导入比例", None))
        self.pushButton_2.setText(_translate("main", "检验比例", None))
        self.pushButton_3.setText(_translate("main", "预估模型", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("main", "TPS", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("main", "CPU占用率", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("main", "最大TPS", None))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)


app=QtGui.QApplication(sys.argv)

win=Ui_main()

win.show()

sys.exit(app.exec_())